steps:
# This step could install Python libraries if you had a requirements.txt
# - name: 'gcr.io/cloud-builders/python'
#   entrypoint: 'pip'
#   args: ['install', '-r', 'requirements.txt']
  
# This step runs your main processing script
- name: 'gcr.io/cloud-builders/python'
  entrypoint: 'python'
  args: [
    './processing_script.py',
    '--file-path', '${_GCS_PATH}' # This is a variable we will pass from our Cloud Function
  ]
